### ISSUE TITLE
JSON array of objects

### ISSUE THREAD

**Issue by jcalfee** [ScaleLeap/pg-format#5]
How do I get a single array like this:
```sql
# select '[{"a": 1}, {"b": 2}]'::jsonb;
        jsonb         
----------------------
 [{"a": 1}, {"b": 2}]
```
instead of separate jsonb array elements like this:
```node
> literal([{a:1}, {b:2}])
`'{"a":1}'::jsonb,'{"b":2}'::jsonb`
```

**Comment by jcalfee** [comment]
possible work-around
```js
> format('select \'[%s]\'::jsonb', [{a:1}, {b:2}])
`select '[{"a":1},{"b":2}]'::jsonb`
```

**Comment by moltar** [comment]
@jcalfee Tbh, not sure, never had this need.

I mostly just rewrote the package to TypeScript from prior art:

https://github.com/ScaleLeap/pg-format#authors-or-acknowledgments

**Comment by moltar** [comment]
If you add a test case, I can try and add this functionality:

https://github.com/ScaleLeap/pg-format/blob/master/src/pg-format.test.ts

**Comment by jcalfee** [comment]
I don't know how you would support this at this point without breaking the API..  Hope that is a good work-around.

**Comment by moltar** [comment]
How about:

```ts
format('SELECT %L::jsonb', JSON.stringify([{a:1}, {b:2}]))
```

```sql
SELECT '[{"a":1},{"b":2}]'::jsonb 
```

https://codesandbox.io/s/pensive-goldstine-hswgtn?file=/src/index.ts:62-120
